### ISSUE TITLE
DB connections are not closed

### ISSUE THREAD

**Issue by aagamdoshi** [marioarizaj/serverless-example#1]
I was just going through the medium article to see how db connections are closed, and found that the connections are not closed and are open , let me know if I have missed it or if you have any other sample repo which closes the connection

**Comment by marioarizaj** [comment]
Hi, 
Thank you for your comment. 
The reason I keep the database connection open is because the lambdas are reusing the same execution context for multiple requests. If you look at how storage is initiated, it only spins up a new connection when there is none. 
When the execution context is stopped for a set of requests it will automatically sever the connection. 
This way the latency is lower when there is a significant load.
